Add proposal to change URL section in API Guidelines
digipolisgent/api-guidelines pull request #3
Opened 2018-11-12 10:16 UTC by ghijsma

2018-11-12 10:24 UTC, daften requested changes
In general the keywords SHOULD, MUST ,... have to be capitalized.

2018-11-12 10:24 UTC, daften commented on Guidelines.md
> +#### 7.1.3 Service namespace
This is very specific for services that will be on the API manager, not necessarily for backend API's. This means this shouldn't go in the general guidelines.

2018-11-12 10:24 UTC, daften commented on Guidelines.md
> +#### 7.1.4 Version
This is already present in chapter 12: versioning.

2018-11-12 10:24 UTC, daften commented on Guidelines.md
> +#### 7.1.5 Resource reference
This is already present in 9.3

2018-11-12 10:24 UTC, daften commented on Guidelines.md
> +#### 7.1.6 Baseurl
Why would we need to define this, it isn't used anywhere else in the document?

2018-11-12 10:24 UTC, daften commented on Guidelines.md
> +#### 7.1.2 Hostname
This shouldn't be in here, this is simple common sense. This is not an API guideline.

2018-11-12 10:24 UTC, daften commented on Guidelines.md
> +#### 7.1.1 URL construction
Why define a 7.1.1 if there is no 7.1.2?

2018-11-12 10:39 UTC, ghijsma commented on Guidelines.md
> +#### 7.1.6 Baseurl
I'll remove this as it is not being used elsewhere.

2018-11-12 10:47 UTC, ghijsma commented on Guidelines.md
> +#### 7.1.3 Service namespace
To be discussed on the next API workgroup. The whole point of this section is to make sure that the organisation uses the "consistency fundamentals". Service namespace is something we want to introduce for all services. This makes deploying them to the API manager easier. It also makes it easier to put all services into perspective business wise. If necessary we can divide this into two categories of services, the ones deployed on API manager and those that are not?

2018-11-12 10:48 UTC, ghijsma commented on Guidelines.md
> +#### 7.1.4 Version
Again here we want to introduce the **MAJOR** version into all API URL's for consistency and better use in the API manager. We may shorten this chapter and make a reference to chapter 12? Also to be discussed on the next API workgroup.

2018-11-12 10:50 UTC, ghijsma commented on Guidelines.md
> +#### 7.1.2 Hostname
I'll also remove this.

2018-11-12 10:57 UTC, ghijsma commented on Guidelines.md
> +#### 7.1.5 Resource reference
A collection is the same as a resource? We can squash this together by making the use of this identifier obligatory and setting a reference in 7.1 to 9.3? Again, for consistency and better use in the API manager.

2018-11-12 10:59 UTC, ghijsma commented on Guidelines.md
> +#### 7.1.1 URL construction
There was / is? Am going to change 7.1 back to **URL structure** with sub-headers: 

- 7.1.1 URL construction
- 7.1.2 Service namespace
- 7.1.3 Version
- 7.1.4 Resource reference

2018-12-13 09:44 UTC, bartlannoeye commented
Besloten op API overleg: Toevoegen als apart chapter, vanuit sectie kan verwezen worden naar de secties.

Voorbeeld business domains (oplijsten in dit chapter):
- supporting
- crm
- location
- finances

2018-12-17 09:26 UTC, bartlannoeye commented
Nieuw hoofdstuk kan vlot van master starten, zal deze dus sluiten.

2018-12-17 09:26 UTC, closed without merging